name: Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  TARGET: thumbv6m-none-eabi

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo +nightly test --verbose
    
